name: Dockerhub Build/Push

on:
  push:
    branches: [ main, dev ]
    paths-ignore: [ "**/README.md", "**/compose.yaml" ]
  pull_request:
    branches: [ main, dev ]
    paths-ignore: [ "**/README.md", "**/compose.yaml" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Branch
      run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: sholt0r
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: sholt0r/checkit:${{ env.BRANCH }}
        build-args: |
          BRANCH=${{ env.BRANCH }}
