name: Dockerhub Build/Push

on:
  push:
    branches: [ main, dev ]
    paths-ignore: [ "**/README.md", "**/compose.yaml" ]
  pull_request:
    branches: [ main, dev ]
    paths-ignore: [ "**/README.md", "**/compose.yaml" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Get Secrets
      uses: bitwarden/sm-action@v2
      with:
        access_token: ${{secrets.BITWARDEN_AT}}
        base_url: https://vault.bitwarden.com
        secrets: |
          359eca86-fe87-41dc-9888-b20501874e56 > DOCKERHUB_TOKEN

    - name: Branch Name
      run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: sholt0r
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: sholt0r/checkit:${{ env.BRANCH }}
        build-args: |
          BRANCH=${{ env.BRANCH }}

