name: Dockerhub Build/Push

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "**/README.md", "**/compose.yaml" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ "**/README.md", "**/compose.yaml" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Get Secrets
      uses: bitwarden/sm-action@v2
      with:
        access_token: ${{secrets.BITWARDEN_AT}}
        base_url: https://vault.bitwarden.com
        secrets: |
          9a5638e8-eabb-47ce-b5c4-b205018735b5 > DOCKERHUB_USERNAME
          359eca86-fe87-41dc-9888-b20501874e56 > DOCKERHUB_TOKEN
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}
    - name: Build and push the Docker image
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/checkit .
        docker push ${{ env.DOCKERHUB_USERNAME }}/checkit