name: Dockerhub Build/Push

on:
  push:
    branches: [ "main", "dev" ]
    paths-ignore: [ "**/README.md", "**/compose.yaml" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push the Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/checkit .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/checkit